### ISSUE TITLE
the `Foo` module seems like annoying boilerplate

### ISSUE THREAD

**Issue by jaredly** [chenglou/reason-react-example#6]
I tried to get rid of it and just do
```re
module WholeThing = {
  include ReactRe.CreateComponent {
    include ReactRe.Component;
    let name = "Foo";
    type props = {message: string};
    let render {props} => <div> (ReactRe.stringToElement props.message) </div>;
  };
  let createElement ::message => wrapProps {message: message};
};
```

but I got this fascinating error

```
Error: This functor has type
       functor (CompleteComponentSpec : ReactRe.CompleteComponentSpec) ->
         sig
           val comp : ReactRe.reactClass
           val wrapProps :
             CompleteComponentSpec.props ->
             children:ReactRe.reactElement list ->
             ?ref:(ReactRe.reactRef -> unit) ->
             ?key:string -> unit -> ReactRe.reactElement
         end
       The parameter cannot be eliminated in the result type.
        Please bind the argument to a module identifier.
```

Which appears to be saying that it actually requires you to make an intermediate module `Foo`.

Any idea what's going on? It'd be rather annoying to have to do this everywhere

**Comment by jordwalke** [comment]
We need to get some BetterErrors up in here (in the rehydrate examples)!

This is strange because in my earlier React prototypes, I could easily use the pattern you showed.

**Comment by chenglou** [comment]
@jordwalke how do we solve this?

**Comment by jordwalke** [comment]
Did a bit of digging. I didn't experience the same issue with my previous typed sketch of the React API so I suspected it would be possible here. By moving the record type outside of the inner module it works.

Here's the code before:

```reason
module Page = {
  include ReactRe.Component;
  type props = {message: string};
  let name = "Page";
  let handleClick _ _ => {
    Js.log "clicked!";
    None
  };
  let render {props, updater} =>
    <div onClick=(updater handleClick)> (ReactRe.stringToElement props.message) </div>;
};
include ReactRe.CreateComponent Page;
let createElement ::message => wrapProps {message: message};
```


Here's the code after:

```reason
type pageProps = {message: string};

include ReactRe.CreateComponent {
  include ReactRe.Component;
  type props = pageProps;
  let name = "Page";
  let handleClick _ _ => {
    Js.log "clicked!";
    None
  };
  let render {props, updater} =>
    <div onClick=(updater handleClick)> (ReactRe.stringToElement props.message) </div>;
};

let createElement ::message => wrapProps {message: message};
```

I had to bring the `props` definition outside of the inner module so that the final `createElement` constructor helper would see it, and then I also had to rename the `type props = ` outside to `type pageProps =` so that it didn't appear cyclical within `Page`. You could have also done `type nonrec props = props` inside of `Page` though if you really wanted to.

If you change the record type to any other type `type props = list`, then it works. That's somewhat expected as this is about record label fields. The bug here is that the error message seems to be misleading at the compiler level - I would be very interested to try on 4.03/4.04. If it's not fixed there, we'll file a mantis issue and get this fixed.

**Comment by jaredly** [comment]
Why doesn't the `createElement` constructor helper see it when the `CreateComponent` result is `include`d?

**Comment by jordwalke** [comment]
In this case, I believe it's because the record field labels are not in "scope". I don't see why they couldn't be though.
This would not be a problem if `props` were an Object or tuple (which are structurally typed).

**Comment by jordwalke** [comment]
What I've been doing (even without React / Rehydrate modules), is I've been defining types within a module like:


```reason
module Types = {
    type pageProps = {x: int, y: int};
    type someVariant = | Foo | Bar;
};
```

The reason is that then I can easily open them as a consumer of this file, without having to open the full module.

```
open Page.Types;
```

Which then makes sure I can see all the variant labels and record labels etc.


This isn't needed when all your types are *structural* - so objects and polymorphic variants as opposed to records and variants. But those also come with tradeoffs (readability of error messages, and a slight performance hit).

The originally reported error message just looks wrong though. It could be a compiler bug, and I'm looking forward to trying when BuckleScript upgrades to 4.03.

Aside from that, I also wonder if 4.03 allows embedding of the `type props` to be visible. That seems less likely.

**Comment by chenglou** [comment]
Solved in the new API at https://github.com/reasonml/reason-react
